server:
  port: 50000

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_test
    username: test
    password: test
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
