CREATE TABLE IF NOT EXISTS t_todo
(
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    title VARCHAR(200) NULL DEFAULT NULL COMMENT 'title',
    completed BOOLEAN NULL DEFAULT NULL COMMENT 'completed',
    create_time DATETIME NOT NULL COMMENT 'create time',
    update_time DATETIME NULL DEFAULT NULL COMMENT 'update time',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
